[window]
decorations = "full"
dynamic_title = false
dynamic_padding = false
opacity = 0.975
title = "Alacritty"
blur = true

[window.padding]
x = 12
y = 20

[font]
size = 10.0

[terminal]
shell = { program = "/bin/zsh" }

[mouse]
hide_when_typing = true
